import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import AuthLayout from '../components/AuthLayout'
import Input from '../components/common/Input'
import Button from '../components/common/Button'
import api from '../api/axios'
import { 
  validateEmail, 
  validateRequired, 
  validatePassword, 
  validateName,
  validatePasswordMatch,
  validateEmployeeId,
  getValidationError 
} from '../utils/validators'

const Signup = () => {
  const navigate = useNavigate()
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    password: '',
    password_confirmation: '',
    role: 'employee', // Employee only - admin cannot sign up
    // Note: employee_id is auto-generated by system
  })
  const [errors, setErrors] = useState({})
  const [apiError, setApiError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }))
    }
    if (apiError) setApiError('')
  }

  const validateForm = () => {
    const newErrors = {}

    // Validate name
    if (!validateRequired(formData.name)) {
      newErrors.name = getValidationError('name', formData.name)
    } else if (!validateName(formData.name)) {
      newErrors.name = getValidationError('name', formData.name)
    }

    // Validate email
    if (!validateRequired(formData.email)) {
      newErrors.email = getValidationError('email', formData.email)
    } else if (!validateEmail(formData.email)) {
      newErrors.email = getValidationError('email', formData.email)
    }

    // Validate phone (optional but if provided should be valid)
    if (formData.phone && formData.phone.trim().length > 0) {
      const phoneRegex = /^[+]?[(]?[0-9]{1,4}[)]?[-\s.]?[(]?[0-9]{1,4}[)]?[-\s.]?[0-9]{1,9}$/
      if (!phoneRegex.test(formData.phone)) {
        newErrors.phone = 'Please enter a valid phone number'
      }
    }

    // Validate password
    if (!validateRequired(formData.password)) {
      newErrors.password = getValidationError('password', formData.password)
    } else if (!validatePassword(formData.password)) {
      newErrors.password = getValidationError('password', formData.password)
    }

    // Validate password confirmation
    if (!validateRequired(formData.password_confirmation)) {
      newErrors.password_confirmation = getValidationError('password_confirmation', formData.password_confirmation, { password: formData.password })
    } else if (!validatePasswordMatch(formData.password, formData.password_confirmation)) {
      newErrors.password_confirmation = getValidationError('password_confirmation', formData.password_confirmation, { password: formData.password })
    }

    // Validate role (optional, defaults to employee)
    if (formData.role && !['admin', 'employee'].includes(formData.role)) {
      newErrors.role = 'Role must be either admin or employee'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setApiError('')

    if (!validateForm()) {
      return
    }

    setLoading(true)

    try {
      const response = await api.post('/register', {
        name: formData.name,
        email: formData.email,
        password: formData.password,
        password_confirmation: formData.password_confirmation,
        role: 'employee', // Force employee role
        phone: formData.phone || null,
      })
      
      if (response.data.status) {
        // Save token and user data
        localStorage.setItem('token', response.data.token)
        localStorage.setItem('user', JSON.stringify(response.data.user))
        
        // Redirect to employee dashboard (signup always creates employee)
        navigate('/employee/dashboard')
      }
    } catch (error) {
      if (error.response?.data) {
        const errorData = error.response.data
        
        if (errorData.errors) {
          // Validation errors from backend
          const backendErrors = {}
          Object.keys(errorData.errors).forEach(key => {
            backendErrors[key] = errorData.errors[key][0]
          })
          setErrors(backendErrors)
        } else {
          setApiError(errorData.message || 'Registration failed. Please try again.')
        }
      } else {
        setApiError('Network error. Please check your connection.')
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthLayout showLogo={true}>
      <div className="page-title">Employee Sign Up</div>
      <form onSubmit={handleSubmit} className="auth-form">
        {apiError && <div className="alert alert-error">{apiError}</div>}

        <div className="input-group">
          <label htmlFor="name">Full Name:-</label>
          <Input
            type="text"
            name="name"
            id="name"
            placeholder="Enter Full Name"
            value={formData.name}
            onChange={handleChange}
            error={errors.name}
            required
            noWrapper={true}
          />
          {errors.name && <span className="error-message">{errors.name}</span>}
        </div>

        <div className="input-group">
          <label htmlFor="email">Email:-</label>
          <Input
            type="email"
            name="email"
            id="email"
            placeholder="Enter Email"
            value={formData.email}
            onChange={handleChange}
            error={errors.email}
            required
            noWrapper={true}
          />
          {errors.email && <span className="error-message">{errors.email}</span>}
        </div>

        <div className="input-group">
          <label htmlFor="phone">Phone:-</label>
          <Input
            type="tel"
            name="phone"
            id="phone"
            placeholder="Enter Phone Number"
            value={formData.phone}
            onChange={handleChange}
            error={errors.phone}
            noWrapper={true}
          />
          {errors.phone && <span className="error-message">{errors.phone}</span>}
        </div>

        <div className="input-group">
          <label htmlFor="password">Password:-</label>
          <Input
            type="password"
            name="password"
            id="password"
            placeholder="Enter Password"
            value={formData.password}
            onChange={handleChange}
            error={errors.password}
            required
            noWrapper={true}
          />
          {errors.password && <span className="error-message">{errors.password}</span>}
        </div>

        <div className="input-group">
          <label htmlFor="password_confirmation">Confirm Password:-</label>
          <Input
            type="password"
            name="password_confirmation"
            id="password_confirmation"
            placeholder="Confirm Password"
            value={formData.password_confirmation}
            onChange={handleChange}
            error={errors.password_confirmation}
            required
            noWrapper={true}
          />
          {errors.password_confirmation && <span className="error-message">{errors.password_confirmation}</span>}
        </div>

        <Button type="submit" loading={loading} variant="primary" className="signup-btn">
          Sign Up
        </Button>

        <div className="auth-footer">
          <p>
            Already have an account ?{' '}
            <Link to="/login" className="auth-link">
              Sign In
            </Link>
          </p>
        </div>
      </form>
    </AuthLayout>
  )
}

export default Signup

